### ISSUE TITLE
Performance issue when trying to visualize postgres datasource

### ISSUE THREAD

**Issue by connectwise-amar-kutwal** [flant/grafana-statusmap#116] opened 2020-07-17 13:51 UTC
Hello Team,

We are trying to have a dashboard using statusmap plugin. We are using Postgres as a datasource and and visualization through statusmap-0.2.0 and grafana-7.0
We are facing following issues while using statusmap
1. Its slows down the browser.
2. It takes more than a minute or sometime 2; to load the dashboard.
3. Once we select the dashboard most of the functions/ options are unavailable for us.

We are using following query to load the data in statusmap

SELECT
  (functtimestamp at time zone 'utc' at time zone 'utc') as "time",
  CONCAT(appname,' ',functname) as metric,
  final_functstatus
FROM funct_heartbeat_monitor
order by time

Attached pannel json for reference
[pannel json.zip](https://github.com/flant/grafana-statusmap/files/4938156/pannel.json.zip)

**Comment by continuum-harsh-shete** [comment] 2020-07-17 13:53
hi team,

Do let us know if PostgreSQL is supported, or we need to user mysqldb or influxDB

**Comment by diafour** [comment] 2020-07-17 14:54
Hello!

Panel plugins (and statusmap as well) receive data from a datasource in a simple format and this format is identical for almost all datasources, so PostgreSQL should be supported.

Most likely the problem with a slow browser is caused by a huge amount of data from datasource. There was a change in Grafana 6.7 related to `${__interval}` variable and the plugin receives data point for each pixel. This was fixed recently and new version 0.3.0 should not suffer from this problem. This version is not available through GF_INSTALL_PLUGINS for now, you need to clone flant/grafana-statusmap repository to try the new version. ([PR#680](https://github.com/grafana/grafana-plugin-repository/pull/680) should be merged by Grafana team).

If you have problems with 0.3.0, please, share this information for further investigation:
- a CREATE TABLE expression for `funct_heartbeat_monitor` table
- an approximate number of unique values in `metrics` column (a number of rows on a panel)
- a dump of data ("Download CSV" button in Edit mode)
- browser and OS version
- do you experience a slowdown for small time ranges (e.g. "Last 5 minutes" or smaller)?
- do you use any data transformers (new feature of Grafana 7)?

**Comment by connectwise-amar-kutwal** [comment] 2020-07-20 08:24
Hello,

Thank you for your reply.
I have updated statusmap version to 0.3.0 and restarted the grafana server.
Now whenever I am switching to visualization as statusmap I am getting following error 
"TypeError: Cannot read property 'emit' of undefined"

Attached screenshot for the reference
![image](https://user-images.githubusercontent.com/66000380/87915981-78434f80-ca90-11ea-81e8-3d3b26f54a57.png)

Thank You.

**Comment by diafour** [comment] 2020-07-20 09:11
Please, give more information:
- screenshot of query definition
- Grafana version
- an error from developer console.

**Comment by connectwise-amar-kutwal** [comment] 2020-07-20 10:03
Hello,

Query definition and the Grafana version is as follows and same is already mentioned in above comment.
**Grafana Version** - 7.0

**Query Defination**
SELECT
  (functtimestamp at time zone 'utc' at time zone 'utc') as "time",
  CONCAT(appname,' ',functname) as metric,
  final_functstatus
FROM funct_heartbeat_monitor
order by time

**Error message from the log file**
t=2020-07-20T07:49:56+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/api/v1/label/__name__/values remote_addr=10.50.150.26 referer="http://172.30.0.115:3000/dashboard/new?editPanel=2&orgId=1" error="http: proxy error: http: no Host in request URL"
t=2020-07-20T07:49:56+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/label/__name__/values status=502 remote_addr=10.50.150.26 time_ms=1 size=0 referer="http://172.30.0.115:3000/dashboard/new?editPanel=2&orgId=1"

**Comment by diafour** [comment] 2020-07-20 12:07
I mean "Query" definition in panel options. Do you use "Time series" format there?

<img width="725" alt="Снимок экрана 2020-07-20 в 14 10 40" src="https://user-images.githubusercontent.com/1055474/87931830-16d0b000-ca93-11ea-9901-0a4754fb9d7b.png">


An error in developer console should be shown when you press F12 in Chrome or choose "Developer tools" in menu. There should be more details about "TypeError: Cannot read property"

<img width="730" alt="Снимок экрана 2020-07-20 в 15 07 21" src="https://user-images.githubusercontent.com/1055474/87935999-c65d5080-ca9a-11ea-8fc5-8d7e1b357363.png">

**Comment by connectwise-amar-kutwal** [comment] 2020-07-20 12:44
Hello,
Please find below screenshot for the reference (output when we select visualization method as statusmap)
 
![image](https://user-images.githubusercontent.com/66000380/87938667-8acf8000-cab4-11ea-979a-1681c68df105.png)

Also please find attached log file from browser console
[console_error.zip](https://github.com/flant/grafana-statusmap/files/4947718/console_error.zip)

**Comment by diafour** [comment] 2020-07-20 13:32
Just to be sure, do you use Grafana v7.0.**6** or another previous release?

**Comment by connectwise-amar-kutwal** [comment] 2020-07-20 14:20
Grafana version we are using currently is **Grafana v7.1.0**

**Comment by diafour** [comment] 2020-07-20 15:18
Ok. There were no tests with v7.1.0. I need more time to investigate the latest changes in Grafana.

Can you test your PostgreSQL queries with Grafana v7.0.6 and statusmap 0.3.0?

**Comment by connectwise-amar-kutwal** [comment] 2020-07-21 10:57
Hello,
I have tested the data using PostgreSQL queries with Grafana v7.0.6 and statusmap 0.3.0. The performance is a way better than what we have in Grafana v7.1.0 . I am still monitoring the performance.
Thank you

**Comment by diafour** [comment] 2020-07-21 14:53
Fix for Grafana 7.1.0 is merged to master branch.

**Comment by connectwise-amar-kutwal** [comment] 2020-07-22 10:41
Thank you. We will test and will share the feedback.

**Comment by diafour** [comment] 2020-08-24 11:59
@connectwise-amar-kutwal Hello! Any updates on your experience with Grafana 7.1.0 and the latest grafana-statusmap?

**Comment by connectwise-amar-kutwal** [comment] 2020-08-24 14:02
Hi, 
Its is working fine on Grafana 7.1.0 as well. Thank you so much 👍

**Closed** 2020-08-24 21:56 UTC
