### ISSUE TITLE
Grafana 7.2 support

### ISSUE THREAD

**Issue by TaylorMutch** [flant/grafana-statusmap#135] opened 2020-09-25 22:26 UTC
When upgrading to Grafana 7.2.0 from 7.1.5, this plugin no longer functions properly; dashboards no longer load which use this plugin. Is this a known issue? Are others hitting this problem?

**Comment by jangmarker** [comment] 2020-09-27 20:27
I'm seeing a similar issue - the dashboard is loading, but the status map panels just don't show any content except for the legend.

**Comment by winestein** [comment] 2020-09-28 13:15
I would also appreciate support for 7.2!

**Comment by diafour** [comment] 2020-09-28 13:50
Thanks for the report! I'll check asap.

**Comment by pep3l** [comment] 2020-09-29 06:05
nice work 0.x release

**Comment by jbfavre** [comment] 2020-09-29 07:01
@diafour Trying to troubleshoot this issue, I figured out I hadn't the latest version.
Tried to install 0.3.3 and found few issues:

- Grafana.com only reference 0.3.2
- 0.3.3 is available on github, but `dist/plugin.json` indicates 0.3.2 as version which I guess makes grafana to stick on 0.3.2

**Comment by pep3l** [comment] 2020-09-29 07:04
> @diafour Trying to troubleshoot this issue, I figured out I hadn't the latest version.
> Tried to install 0.3.3 and found few issues:
> 
> * Grafana.com only reference 0.3.2
> * 0.3.3 is available on github, but `dist/plugin.json` indicates 0.3.2 as version which I guess makes grafana to stick to 0.3.2

same problem with me

**Comment by christianversloot** [comment] 2020-10-08 10:50
Hitting the problem as well. I installed what is published here as `0.3.3` but doing so didn't resolve the isuse.

**Comment by diafour** [comment] 2020-10-09 08:44
So, the problem is confirmed. I've tried to run 7.2.0 and the plugin not works. No errors, no messages, just a blank panel in a View mode. Edit mode is slightly better, the plugin shows buckets when the query is entered for the first time (I've tried the Prometheus datasource). The next edits do nothing, the plugin shows first state.
Sorry, no hotfix or workaround for now. Will check issues in Grafana and analyze changes.

**Comment by christianversloot** [comment] 2020-10-09 08:54
Great, thanks!!

**Comment by diafour** [comment] 2020-10-12 07:57
The fix is in the master branch. Also, I will cut a new release soon.

The problem was with renames in Grafana source code, see https://github.com/grafana/grafana/issues/28175 for details.

**Closed** 2020-10-15 12:00 UTC
Labels: bug

**Comment by zameeransari** [comment] 2021-02-10 12:55
Upgraded our Grafana instance from 6.7.2 to 7.3.6, all our dashboards which are using statusmap plugin went blank. 0.3.4 version is installed, also tried immediate previous 0.3.2 but didn't worked. Now migrating dashboards to heatmap. No idea why it is not working, is it known compatibility issue?

**Comment by christianversloot** [comment] 2021-02-10 13:22
@zameeransari see #169 which is for `7.4.0`. Likely, there are issues with `7.3.6` too -- which is something that happens when the software where you plug into is changed. It may be the case that a fix for `7.4.0` will work for `7.3.6` too, but it may not be the case. In that case, you can either upgrade to `7.4.0` if #169 is fixed or file a new issue for `7.3.6` support.
