### ISSUE TITLE
Value is not showing properly on the tooltip as per metric in the Grafana dashboard

### ISSUE THREAD

**Issue by Himanshi-Patle** [flant/grafana-statusmap#137] opened 2020-09-30 08:59 UTC
Hi Team,

I am seeing the issue in the dashboard that, sometimes value, date and metric name on the tooltip is not showing properly like for the particular metric and date, I am seeing the value for another metric. I can see the color wise it is showing properly based on legend range and color. but on tooltip I am seeing something different for some metrics and for sometime.

I have used SQL server as datasource and Statusmap panel for Grafana by Flant, version is 0.2.0 and the Grafana version is 6.7.2

If you know why it is happening, please provide the solution

**Comment by shurup** [comment] 2020-09-30 09:09
Hello and thank you for your issue!

We have newer releases of grafana-statusmap (v0.3.x) where rendering for a variety of Grafana versions (including v6.7) has been fixed. Grafana-statusmap v0.3.2 is available in [Grafana Plugins directory](https://grafana.com/grafana/plugins/flant-statusmap-panel) as well. Can you please check it in your case? Let us know if that works!

**Comment by Himanshi-Patle** [comment] 2020-09-30 09:14
Thanks for the quick response Shurup

I will check and let you know whether it is working or not.

**Comment by Himanshi-Patle** [comment] 2020-09-30 10:37
When I used Azure Data Explorer as a datasource and selected the statusmap plugin, it is working fine for the same version of the plugin(0.2.0).

So version upgradation will be helpful for my issue or anything else ?

**Comment by diafour** [comment] 2020-09-30 10:50
Hello! Please, use version 0.3.2. It has fixes for tooltips (https://github.com/flant/grafana-statusmap/issues/70) and better compatibility with 6.7+ (https://github.com/flant/grafana-statusmap/issues/102).

**Comment by Himanshi-Patle** [comment] 2020-09-30 11:18
After upgradation I can't see the name of the metric in tooltip
see the below screenshot
![image](https://user-images.githubusercontent.com/72122929/94678709-889f6280-033c-11eb-8b8a-781b64104629.png)

**Comment by Himanshi-Patle** [comment] 2020-10-05 05:10
does anyone knows how can we see the name of metrics for the above screenshot?

**Comment by diafour** [comment] 2020-10-09 08:35
Hello! I've checked the problem with 'name'. The problem is a typo in tooltip.ts file, 'name' only shows in 'discrete' mode. The fix will be in master branch soon.

**Closed** 2020-10-10 10:11 UTC

**Comment by Himanshi-Patle** [comment] 2020-10-14 05:19
does gradient modes is called  as spectrum mode ?

**Comment by diafour** [comment] 2020-10-15 07:29
There are two variants for gradient: opacity and spectrum.

**Comment by Himanshi-Patle** [comment] 2020-10-16 09:23
Hi Team,
If I am using 1h in this query  "$__timeGroup(date, '1h') as time", then I am seeing the two values and if I used '2h' instead of '1h' then it is showing only one value, please tell me why I am seeing two values.
![image](https://user-images.githubusercontent.com/72122929/96241148-686bd680-0fbf-11eb-84f2-7ea40bb3c405.png)

**Comment by diafour** [comment] 2020-10-16 12:15
This happens because the bucket's interval is 2h. 1h interval gives 2 values for 2h interval. Use Grafana's `$__interval` variable to set a proper interval related to the dashboard range: https://github.com/flant/grafana-statusmap#mysql

**Comment by Himanshi-Patle** [comment] 2020-10-17 12:36
Hi Team,
I want to add threshold in statusmap , is it possible?
As I am having values from 1 to 40000 so color of 1 and 1100 are similar 
I want to see color of 1 and 100 will be different in statusmap
or different plugin will work like the same ?

**Comment by diafour** [comment] 2020-10-18 21:46
Sorry, there are no threshold settings for now. Please, adjust the query or try the "Transformations" feature from Grafana 7. 

There is a plan to support some kind of logical expressions for discrete mode (#75) in the future versions.
